import 'dotenv/config';
import { Client, GatewayIntentBits, EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle, ModalBuilder, TextInputBuilder, TextInputStyle, REST, Routes } from 'discord.js';
const client=new Client({intents:[GatewayIntentBits.Guilds]});
const BACKEND=process.env.BACKEND_INTERNAL_URL;
const SECRET=process.env.BACKEND_INTERNAL_SECRET;
const OWNER=process.env.MAIN_OWNER_DISCORD_ID || '1446502651637534772';
function api(path,opts={}){return fetch(`${BACKEND}${path}`,{...opts,headers:{'Content-Type':'application/json','x-internal-secret':SECRET,...(opts.headers||{})}}).then(async r=>{const t=await r.text(); let j={}; try{j=JSON.parse(t)}catch{j={raw:t}} if(!r.ok)throw new Error(j.error||t); return j})}
function isAdmin(member, roleId){return member.id===OWNER || member.permissions.has('Administrator') || member.permissions.has('ManageGuild') || (roleId && member.roles.cache.has(roleId));}
async function registerCommands(){const commands=[{name:'setup',description:'Post AhnajakMC Store UI in this channel',options:[{name:'admin_role',description:'Role allowed to use setup',type:8,required:false}]}]; const rest=new REST({version:'10'}).setToken(process.env.DISCORD_TOKEN); if(process.env.DISCORD_GUILD_ID) await rest.put(Routes.applicationGuildCommands(process.env.DISCORD_CLIENT_ID,process.env.DISCORD_GUILD_ID),{body:commands}); else await rest.put(Routes.applicationCommands(process.env.DISCORD_CLIENT_ID),{body:commands});}
async function storeRows(guildId){const cats=await api(`/api/categories?guild_id=${guildId}`,{method:'GET'}).catch(()=>({categories:[]})); const rows=[]; let row=new ActionRowBuilder(); cats.categories.slice(0,20).forEach((c,i)=>{if(i>0&&i%5===0){rows.push(row); row=new ActionRowBuilder()} row.addComponents(new ButtonBuilder().setCustomId(`cat:${c.id}`).setLabel(c.name.slice(0,80)).setStyle(ButtonStyle.Primary));}); if(row.components.length) rows.push(row); rows.push(new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('howto').setLabel('How to Use').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('terms').setLabel('Terms & Privacy').setStyle(ButtonStyle.Secondary))); return rows;}
client.once('ready',async()=>{console.log(`Logged in as ${client.user.tag}`); try{await registerCommands()}catch(e){console.error('Command register failed:',e.message)}});
client.on('interactionCreate',async i=>{try{
 if(i.isChatInputCommand() && i.commandName==='setup'){
  const role=i.options.getRole('admin_role'); if(!isAdmin(i.member, role?.id)) return i.reply({content:'❌ You need Administrator/Manage Server permission.',ephemeral:true});
  await api('/api/setup',{method:'POST',body:JSON.stringify({guild_id:i.guildId,guild_name:i.guild.name,admin_user_id:i.user.id,admin_role_id:role?.id||null})});
  const embed=new EmbedBuilder().setTitle('ᴀʜɴᴀᴊᴀᴋᴍᴄ ꜱᴛᴏʀᴇ').setDescription('Select a category below to buy ranks, kits, keys, and more.').setColor(0xf8c85a).setFooter({text:'Powered by AhnajakMC Store'});
  await i.channel.send({embeds:[embed],components:await storeRows(i.guildId)}); return i.reply({content:'✅ Store UI posted.',ephemeral:true});
 }
 if(i.isButton() && i.customId==='howto'){const s=await api(`/api/settings?guild_id=${i.guildId}`,{method:'GET'}); return i.reply({content:s.settings?.how_to_use||'Choose product, enter username, scan KHQR.',ephemeral:true});}
 if(i.isButton() && i.customId==='terms'){const s=await api(`/api/settings?guild_id=${i.guildId}`,{method:'GET'}); return i.reply({content:s.settings?.terms_privacy||'No refund after delivery unless staff approves.',ephemeral:true});}
 if(i.isButton() && i.customId.startsWith('cat:')){const cid=i.customId.split(':')[1]; const p=await api(`/api/products?guild_id=${i.guildId}&category_id=${cid}`,{method:'GET'}); if(!p.products.length)return i.reply({content:'No products in this category yet.',ephemeral:true}); const rows=[]; let row=new ActionRowBuilder(); p.products.slice(0,20).forEach((prod,idx)=>{if(idx>0&&idx%5===0){rows.push(row);row=new ActionRowBuilder()} row.addComponents(new ButtonBuilder().setCustomId(`buy:${prod.id}`).setLabel(`${prod.name} $${prod.price}`).setStyle(ButtonStyle.Success));}); if(row.components.length)rows.push(row); return i.reply({content:'Choose product:',components:rows,ephemeral:true});}
 if(i.isButton() && i.customId.startsWith('buy:')){const pid=i.customId.split(':')[1]; const modal=new ModalBuilder().setCustomId(`modalbuy:${pid}`).setTitle('Minecraft Username'); const input=new TextInputBuilder().setCustomId('username').setLabel('Your Minecraft username').setStyle(TextInputStyle.Short).setRequired(true).setMinLength(3).setMaxLength(16); modal.addComponents(new ActionRowBuilder().addComponents(input)); return i.showModal(modal);}
 if(i.isModalSubmit() && i.customId.startsWith('modalbuy:')){const pid=i.customId.split(':')[1]; const username=i.fields.getTextInputValue('username'); if(!/^[a-zA-Z0-9_]{3,16}$/.test(username))return i.reply({content:'❌ Invalid Minecraft username.',ephemeral:true}); await i.deferReply({ephemeral:true}); const order=await api('/api/orders',{method:'POST',body:JSON.stringify({guild_id:i.guildId,discord_user_id:i.user.id,minecraft_username:username,product_id:pid})}); const embed=new EmbedBuilder().setTitle('⏳ KHQR Payment Pending').setDescription(`Order: **${order.order.transaction_id}**\nProduct: **${order.product.name}**\nUsername: **${username}**\nPrice: **$${order.product.price}**`).setColor(0xf8c85a); if(order.qr?.qrCodeData)embed.setImage(order.qr.qrCodeData); const rows=[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`check:${order.order.transaction_id}`).setLabel('Check Payment').setStyle(ButtonStyle.Primary))]; return i.editReply({embeds:[embed],components:rows});}
 if(i.isButton() && i.customId.startsWith('check:')){const id=i.customId.split(':')[1]; const r=await api(`/api/orders?transaction_id=${id}`,{method:'GET'}); return i.reply({content:`Order ${id} status: **${r.order?.status||'not_found'}**`,ephemeral:true});}
}catch(e){console.error(e); if(i.deferred||i.replied) await i.editReply({content:'❌ '+e.message}).catch(()=>{}); else await i.reply({content:'❌ '+e.message,ephemeral:true}).catch(()=>{})}});
client.login(process.env.DISCORD_TOKEN);
